name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install black flake8 pytest
      - run: black --check .
      - run: flake8
      - name: Run tests if present
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests directory; skipping"
          fi
      - name: Set commit status (CI)
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const targetUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: core.getInput('state') || 'success',
              context: 'CI',
              description: 'CI completed',
              target_url: targetUrl
            });