name: Dependency Audit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install pip-audit
      - name: Run pip-audit (best-effort)
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt || true
          else
            echo "No requirements.txt found; running environment audit"
            pip-audit || true
          fi
      - name: Set commit status (Dependency Audit)
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const targetUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'Dependency Audit',
              description: 'Dependency audit completed',
              target_url: targetUrl
            });